[package]
name = "cursed_phone"
version = "0.1.0"
authors = ["Nicholas Fleck <TheBerkin@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
incremental = true
codegen-units = 1
# lto = true

[features]
rpi = ["rppal"]
no-log = ["log/release_max_level_off", "log/max_level_off"]

[dependencies]
rand = "0.7.3"
rodio = { version = "0.11.0", default-features = false, features = ["wav", "vorbis"] }
globwalk = "0.8.0"
globset = "0.4.5"
enum-iterator = "0.6.0"
indexmap = "1.4.0"
ref-portals = "1.0.0-beta.1"
serde = { version = "1.0.111", features = ["derive"] }
thread-priority = "0.2.0"
toml = "0.5.6"
rppal = { version = "0.11.3", optional = true }
mlua = { version = "0.4.1", default-features = false, features = ["vendored", "luajit"] }
log = { version = "0.4.8" }
simplelog = "0.8.0"