[package]
name = "cursed_phone"
version = "0.1.0"
authors = ["Nicholas Fleck <TheBerkin@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
rpi = ["rppal"]

[dependencies]
rand = "0.7.3"
rodio = "0.11.0"
globwalk = "0.8.0"
globset = "0.4.5"
enum-iterator = "0.6.0"
ref-portals = "1.0.0-beta.1"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
rppal = { version = "0.11.3", optional = true }

[dependencies.mlua]
version = "0.3.2"
default-features = false
features = ["luajit", "vendored"]