--- @meta

--- @class PerlinNoise
C_PerlinNoise = {}

--- Creates a new Perlin noise sampler with the specified parameters.
--- @param octaves integer @ The number of octaves (layers) to add to the noise.
--- @param frequency number @ The number of noise cycles per unit length.
--- @param persistence number @ The amplitude multiplier for each successive octave.
--- @param lacunarity number @ The frequency multiplier for each successive octave.
--- @param seed? integer @ (Optional) The 32-bit seed of the noise generator. If not specified, uses a random seed generated by the global RNG.
--- @return PerlinNoise
function PerlinNoise(octaves, frequency, persistence, lacunarity, seed) end

--- Gets the noise value at the specified coordinates.
--- @param x number @ The X coordinate to sample at.
--- @param y number @ The Y coordinate to sample at.
--- @return number
function C_PerlinNoise:sample(x, y) end